Attribute VB_Name = "Module1"
Public Curpath As String
Public Countsub As Integer
Public countdes As Integer
Public CurFile As String
Public Levelup As String
Public ScriptOne As Boolean
Public TS As String
Public CountStuff As Integer
Public wf As Integer
